### ISSUE TITLE
Create_boolean.ipynb is way to complex

### ISSUE THREAD

**Issue by lperron** [oulianov/cp-sat-fun#1]
You never need bigM. it complicates everything.

```
    # If var > 0, then this is true only if bool = 1
    # If var <= 0, then this is always true
    model.Add(BIG_M*boolean_var >= var)
    # If var > 0, then this is always true
    # If var <= 0, then this is true only if bool = 0
    model.Add(BIG_M*(boolean_var - 1) <= var)
```

just write:

```
  model.Add(var > 0).OnlyEnforceIf(boolean_var)
  model.Add(var <= 0).OnlyEnforceIf(boolean_var).Not())
```

```
    boolean_var = model.NewBoolVar(name=f"{var.Name()}_is_equal_to_{value}")
    model.Add(value * boolean_var == var).OnlyEnforceIf(boolean_var)
    model.Add(value != var).OnlyEnforceIf(boolean_var.Not())
```

when the constraint is enforced, boolean_var is always true, so you can remove it:

```
    boolean_var = model.NewBoolVar(name=f"{var.Name()}_is_equal_to_{value}")
    model.Add(value == var).OnlyEnforceIf(boolean_var)
    model.Add(value != var).OnlyEnforceIf(boolean_var.Not())
```

**Comment by lperron** [comment]
see https://github.com/google/or-tools/blob/stable/ortools/sat/docs/channeling.md

**Comment by oulianov** [comment]
I agree, big M notation is not the best. Happy to implement your feedback and use your simpler version !!
I'll adapt the notebook accordingly

**Comment by lperron** [comment]
The rest really looks good. I am impressed by your non linear notebook.

Thanks and good luck.
Laurent Perron | Operations Research | ***@***.*** | (33) 1 42 68 53
00



Le jeu. 6 avr. 2023 à 12:48, Nicolas Oulianov ***@***.***> a
écrit :

**Comment by oulianov** [comment]
Thank you Laurent, this means a lot to me ! 
I pushed a new version of the notebook.
